name: Athlify
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animations: ^2.0.7
  http: ^1.3.0
  awesome_dialog: ^3.2.1
  shared_preferences: ^2.5.2
  flutter_bloc: ^9.1.1
  dio: ^5.8.0+1
  smooth_page_indicator: ^1.1.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  flutter_native_splash: ^2.2.19
  firebase_core: ^2.32.0
  firebase_messaging: ^14.7.10
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.5
  provider: ^6.1.5
  flutter_local_notifications: ^19.2.1
  flutter_rating_bar: ^4.0.1
  flutter_stripe: ^11.5.0
  dartz: ^0.10.1
  flutter_svg: ^2.2.0
  fl_chart: ^1.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Nasalization
      fonts:
        - asset: assets\fonts\Nasalization Rg.otf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image.png"
  android_adaptive_icon_background: "#ffffff" # or use an image path like "assets/icon_background.png"
  android_adaptive_icon_foreground: "assets/image.png"

flutter_native_splash:
  fullscreen: true
  android_gravity: center
  ios_content_mode: scaleAspectFit
  color: "#ffffff"
  image: assets/image.png
  android: true
  ios: true
